"""
Routing rules: every filename pattern → (archive key, UOSFA folder).

To add a new query, append a Rule to ROUTES.
  archive       - key passed to FileProcessor.get_archive(); see processor.py for the full map
  folder        - UOSFA subfolder name (e.g. "Daily Reports"); use None to archive-only (no UOSFA move)
  flag          - "direct_loan" or "alt_loan" if this file triggers an origination copy
  use_disb_date - rename with disbursement date instead of today
  rename_fn     - override standard rename for the archive copy: callable(filename, year, today_date) -> new_name
  uosfa_name_fn - override rename for the UOSFA destination only: callable(filename, year, today_date) -> new_name
  overwrite     - overwrite the UOSFA destination if it already exists (default: add numeric suffix)
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Callable, Optional


@dataclass
class Rule:
    name: str
    match: Callable[[str, str], bool]   # (filename_no_ext, aid_year) -> bool
    archive: str
    folder: str
    flag: str = ""
    use_disb_date: bool = False
    rename_fn: Optional[Callable[[str, str, str], str]] = None
    uosfa_name_fn: Optional[Callable[[str, str, str], str]] = None
    overwrite: bool = False


# ── Match helpers ──────────────────────────────────────────────────────────
def sw(p):         return lambda q, y: q.startswith(p)
def has(p):        return lambda q, y: p in q
def has_all(a, b): return lambda q, y: a in q and b in q
def has_not(p, e): return lambda q, y: p in q and e not in q
def sw_y(p, s=""): return lambda q, y: q.startswith(f"{p}20{y[-2:]}{s}")

# EOT renames strip the trailing _NNN instance suffix before adding year
def _eot_rename(name: str, year: str, date: str) -> str:
    dot   = name.rfind(".")
    under = name.rfind("_")
    return f"{date} {name[:under]} {year[2:]}{name[dot:]}"

# Award-summary rename: keep original filename, no year suffix
def _award_rename(name: str, year: str, date: str) -> str:
    return f"{date} {name}"

# DB-file UOSFA name: original filename unchanged (no date, no year suffix)
def _db_uosfa_name(name: str, year: str, *_) -> str:
    dot = name.rfind(".")
    return f"{name[:dot]} {year[2:]}{name[dot:]}"


ROUTES: list[Rule] = [

    # ── Daily Reports ──────────────────────────────────────────────────────
    Rule("IL_ATHLETE_OVERAWARD",            has("IL_ATHLETE_OVERAWARD"),            "daily", "Daily Reports"),
    Rule("IL_CMT_CDE_OVR_AGR_LMT",         has("IL_CMT_CDE_OVR_AGR_LMT"),         "daily", "Daily Reports"),
    Rule("IL_COMMENT_CODE_298",             has("IL_COMMENT_CODE_298"),             "daily", "Daily Reports"),
    Rule("IL_FDEG_FFBD_FBLK_FFBC",         has("IL_FDEG_FFBD_FBLK_FFBC"),         "daily", "Daily Reports"),
    Rule("IL_COMPLETE_FDEG",               has("IL_COMPLETE_FDEG"),               "daily", "Daily Reports"),
    Rule("IL_CORR_NOT_MARK_SENT",          has("IL_CORR_NOT_MARK_SENT"),          "daily", "Daily Reports"),
    Rule("UUFA_IL_CORR_SENT_RJCT_CD1",    has("UUFA_IL_CORR_SENT_RJCT_CD1"),    "daily", "Daily Reports"),
    Rule("IL_ATHLETE_RESIDENCY",           has("IL_ATHLETE_RESIDENCY"),           "daily", "Daily Reports"),
    Rule("FA_IL_ENRL_GR_DATE_ERRORS",      sw("FA_IL_ENRL_GR_DATE_ERRORS"),       "daily", "Daily Reports"),
    Rule("UUFA_IL_FBKP",                   sw("UUFA_IL_FBKP"),                    "daily", "Daily Reports"),
    Rule("UUFA_IL_FOUT",                   sw("UUFA_IL_FOUT"),                    "daily", "Daily Reports"),
    Rule("FA_IL_FP1B",                     sw("FA_IL_FP1B"),                      "daily", "Daily Reports"),
    Rule("FA_IL_FP2B",                     sw("FA_IL_FP2B"),                      "daily", "Daily Reports"),
    Rule("FA_IL_FP1N",                     sw("FA_IL_FP1N"),                      "daily", "Daily Reports"),
    Rule("FA_IL_FP2N",                     sw("FA_IL_FP2N"),                      "daily", "Daily Reports"),
    Rule("UUFA_IL_FPJ",                    sw("UUFA_IL_FPJ"),                     "daily", "Daily Reports"),
    Rule("UUFA_IL_ISIR_02_IND_UP_DWN",    sw("UUFA_IL_ISIR_02_IND_UP_DWN"),     "daily", "Daily Reports"),
    Rule("UUFA_IL_FEHU",                   sw("UUFA_IL_FEHU"),                    "daily", "Daily Reports"),
    Rule("UUFA_IL_IRS_DRT_02",             sw("UUFA_IL_IRS_DRT_02"),              "daily", "Daily Reports"),
    Rule("FA_IL_ISIR_CMT_CODE_359_360",    sw("FA_IL_ISIR_CMT_CODE_359_360"),     "daily", "Daily Reports"),
    Rule("UUFA_IL_ISIR_GRD_I_UG_FATRM",   sw("UUFA_IL_ISIR_GRD_I_UG_FATRM"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_ISIR_PRMARY_EFC_DIF",   sw("UUFA_IL_ISIR_PRMARY_EFC_DIF"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_ISIR_LOADED_NOT_PKG",   sw("UUFA_IL_ISIR_LOADED_NOT_PKG"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_LN_EXP_GRAD_DATE",      sw("UUFA_IL_LN_EXP_GRAD_DATE"),       "daily", "Daily Reports"),
    Rule("STDT_WITH_FLPR_INIT",            has("STDT_WITH_FLPR_INIT"),            "daily", "Daily Reports"),
    Rule("IL_STDT_WITH_FLNPR_INIT",        has("IL_STDT_WITH_FLNPR_INIT"),        "daily", "Daily Reports"),
    Rule("UUFA_IL_NURSING_LOANS_TILA",     sw("UUFA_IL_NURSING_LOANS_TILA"),      "daily", "Daily Reports"),
    Rule("FA_IL_OTHER_ATB_20",             sw("FA_IL_OTHER_ATB_20"),              "daily", "Daily Reports"),
    Rule("FA_IL_OTHER_ATTND",              sw("FA_IL_OTHER_ATTND"),               "daily", "Daily Reports"),
    Rule("UUFA_IL_PELL_LEU",               sw("UUFA_IL_PELL_LEU"),                "daily", "Daily Reports"),
    Rule("UUFA_IL_PELL_MAX_ELIG",          sw("UUFA_IL_PELL_MAX_ELIG"),           "daily", "Daily Reports"),
    Rule("UUFA_IL_SF_RFND_AWD_NO_POST",    sw("UUFA_IL_SF_RFND_AWD_NO_POST"),     "daily", "Daily Reports"),
    Rule("UUFA_IL_SUB_ISIR_NO_PACKAGE",    sw("UUFA_IL_SUB_ISIR_NO_PACKAGE"),     "daily", "Daily Reports"),
    Rule("IL_SUB_ISIR_SYSG",               has("IL_SUB_ISIR_SYSG"),               "daily", "Daily Reports"),
    Rule("UUFA_IL_VET_ACTV_DUTY_STAT",     sw("UUFA_IL_VET_ACTV_DUTY_STAT"),      "daily", "Daily Reports"),
    Rule("UUFA_IL_VER_I_SUB_SUSP_ISIR",   sw("UUFA_IL_VER_I_SUB_SUSP_ISIR"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_V5_VER_AFTR_OTH_VER",   sw("UUFA_IL_V5_VER_AFTR_OTH_VER"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_UPDATED_SEC",            sw("UUFA_IL_UPDATED_SEC"),             "daily", "Daily Reports"),
    Rule("UUFA_IL_FATN_INITIATED",         sw("UUFA_IL_FATN_INITIATED"),          "daily", "Daily Reports"),
    Rule("UUFA_IL_FED_AID_OVERAWARD",      sw("UUFA_IL_FED_AID_OVERAWARD"),       "daily", "Daily Reports"),
    Rule("UUFA_IL_ALL_ITEMS_OVERAWARD",    sw("UUFA_IL_ALL_ITEMS_OVERAWARD"),     "daily", "Daily Reports"),
    Rule("UUFA_IL_ALL_ITEM_SUM_OVRAWD",   sw("UUFA_IL_ALL_ITEM_SUM_OVRAWD"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_FHST_I_HST_COMPLETE",   sw("UUFA_IL_FHST_I_HST_COMPLETE"),    "daily", "Daily Reports"),
    Rule("UUFA_REFUND_HOLDS",              sw("UUFA_REFUND_HOLDS"),               "refund",   "Daily Reports"),
    Rule("UUFA_IL_PKG_SCH_EXP_GRAD_FA",   sw("UUFA_IL_PKG_SCH_EXP_GRAD_FA"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_PKG_FED_EXP_GRAD_FA",   sw("UUFA_IL_PKG_FED_EXP_GRAD_FA"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_FPEL",                   sw("UUFA_IL_FPEL"),                    "daily", "Daily Reports"),
    Rule("UUFA_PACKAGING_C_NO_FED_AID",   sw("UUFA_PACKAGING_C_NO_FED_AID"),    "daily", "Daily Reports"),
    Rule("UUFA_PERKINS_NOT_DISBURSED",     sw("UUFA_PERKINS_NOT_DISBURSED"),      "daily", "Daily Reports"),
    Rule("UUFA_ITM_TYPE_NOT_IN_NEXT_AY",  sw("UUFA_ITM_TYPE_NOT_IN_NEXT_AY"),   "daily", "Daily Reports"),
    Rule("UUFA_IL_FREV_CHECKLIST_INT",     sw("UUFA_IL_FREV_CHECKLIST_INT"),      "daily", "Daily Reports"),
    Rule("UUFA_IL_FREV_DOES_NOT_EXIST",    sw("UUFA_IL_FREV_DOES_NOT_EXIST"),     "daily", "Daily Reports"),
    Rule("IL_STU_WITH_06_CODE",            has("IL_STU_WITH_06_CODE"),            "daily", "Daily Reports"),
    Rule("IL_GRNT_UG_5_YR_2BCH",          has("IL_GRNT_UG_5_YR_2BCH"),          "daily", "Daily Reports"),
    Rule("IL_NSLDS_NO_MCH_DB_FLG",         has("IL_NSLDS_NO_MCH_DB_FLG"),         "daily", "Daily Reports"),
    Rule("IL_FAVR_CHKLST_INT",             has("IL_FAVR_CHKLST_INT"),             "daily", "Daily Reports"),
    Rule("QJ23029 (Royall)",               has("QJ23029"),                        "royall","Daily Reports"),
    Rule("IL_RES_NON_RES_BDGT",            has("IL_RES_NON_RES_BDGT"),            "daily", "Daily Reports"),
    Rule("PELL_RPKG_VAR_FLAG_2",           has("PELL_RPKG_VAR_FLAG_2"),           "pell",  "Pell Reports"),
    Rule("UUFA_MR_PELL_NO_ELIG_FLAG",      has("UUFA_MR_PELL_NO_ELIG_FLAG"),      "pell",  "Pell Reports"),
    Rule("IL_3RD_PARTY_EXCEPT",            has("IL_3RD_PARTY_EXCEPT"),            "daily", "Daily Reports"),
    Rule("IL_3RD_PARTY_MAIN_SU",           has("IL_3RD_PARTY_MAIN_SU"),           "daily", "Daily Reports"),
    Rule("IL_3RD_PARTY_MAIN (no SU)",      has_not("IL_3RD_PARTY_MAIN", "SU"),   "daily", "Daily Reports"),
    Rule("IL_3RD_PARTY_NO_BDGT",           has("IL_3RD_PARTY_NO_BDGT"),           "daily", "Daily Reports"),
    Rule("PDQ_SAP_HOLD_DEL",               has("PDQ_SAP_HOLD_DEL"),               "pre_disb","Daily Reports"),
    Rule("SHOPPING_SHEET_UG",              has("SHOPPING_SHEET_UG"),              "pre_disb","Daily Reports"),
    Rule("_IL_REPEAT_COURSES",             has("_IL_REPEAT_COURSES"),             "pre_disb","Daily Reports"),
    Rule("_INCOMPLETE_CHECKLIST",          has("_INCOMPLETE_CHECKLIST"),          "pre_disb","Daily Reports"),
    Rule("IL_SUMMER_AWARDING",             has("IL_SUMMER_AWARDING"),             "pre_disb","Daily Reports"),
    Rule("IL_ISIR_SSN_MISMATCH",           has("IL_ISIR_SSN_MISMATCH"),           "pre_disb","Daily Reports"),
    Rule("UUFA_IL_FCLVER_C_NO_OVERIDE",   has("UUFA_IL_FCLVER_C_NO_OVERIDE"),   "daily", "Daily Reports"),
    Rule("UUFA_IL_FDEGRX_FABCX_FBLKD",    has("UUFA_IL_FDEGRX_FABCX_FBLKD"),    "daily", "Daily Reports"),
    Rule("UUFA_IL_FOVPEL_INITIATED",       has("UUFA_IL_FOVPEL_INITIATED"),       "daily", "Daily Reports"),
    Rule("UUFA_IL_OUTSIDE_RESOURCES",      has("UUFA_IL_OUTSIDE_RESOURCES"),      "daily", "Daily Reports"),
    Rule("_IL_STDNTS_W_ISIRVW",            has("_IL_STDNTS_W_ISIRVW"),            "daily", "Daily Reports"),
    Rule("UUFA_IL_ISIR_C_CODE",            has("UUFA_IL_ISIR_C_CODE"),            "daily", "Daily Reports"),
    Rule("UUFA_EA_SCH_4UT_FS",             has("UUFA_EA_SCH_4UT_FS"),             "ea",    "External Award Reports"),
    Rule("UUFA_EA_SCH79PCT_FS_NO_ATH",     has("UUFA_EA_SCH79PCT_FS_NO_ATH"),     "ea",    "External Award Reports"),
    Rule("UUFA_EA_SCH_ATH_FS",             has("UUFA_EA_SCH_ATH_FS"),             "ea",    "External Award Reports"),
    Rule("UUFA_EA_SCH79PCT_FSU",           has("UUFA_EA_SCH79PCT_FSU"),           "ea",    "External Award Reports"),
    Rule("UUFA_EA_SCH79_FSU",              has("UUFA_EA_SCH79_FSU"),              "ea",    "External Award Reports"),
    Rule("UUFA_JB_SCH_EA_FSU",             has("UUFA_JB_SCH_EA_FSU"),             "ea",    "External Award Reports"),
    Rule("UUFA_SMR_PKG_HI_PELL_LEU",       has("UUFA_SMR_PKG_HI_PELL_LEU"),       "pell",  "Pell Reports"),
    Rule("UUFA_FA_SP_PELL_SUMMER_PKG",     has("UUFA_FA_SP_PELL_SUMMER_PKG"),     "pell",  "Pell Reports"),
    Rule("UUFA_RPKG_HI_PELL_LEU",          has("UUFA_RPKG_HI_PELL_LEU"),          "pell",  "Pell Reports"),
    Rule("UUFA_IL_GTB_REVIEW_BY_TERM",     sw("UUFA_IL_GTB_REVIEW_BY_TERM"),      "daily", "Daily Reports"),
    Rule("UUFA_IL_STDT_W_FLNPR_INIT",      sw("UUFA_IL_STDT_W_FLNPR_INIT"),       "daily", "Daily Reports"),
    Rule("AWARD_LOCK_SNAPSHOT",            has("AWARD_LOCK_SNAPSHOT"),            "daily", "Daily Reports"),
    Rule("UUFA_DELETE_FA_TAKEN",           sw("UUFA_DELETE_FA_TAKEN"),            "daily", "Daily Reports"),
    Rule("UUFA_LOAN_ACC_INC_ORT",          sw("UUFA_LOAN_ACC_INC_ORT"),           "daily", "Daily Reports"),
    Rule("UUFA_UNACCREDITED_HS",           sw("UUFA_UNACCREDITED_HS"),            "daily", "Daily Reports"),
    Rule("UUFA_FATERM_SOURCE_N_AWD_FC",    sw("UUFA_FATERM_SOURCE_N_AWD_FC"),     "daily", "Daily Reports"),
    Rule("UUFA_LDR_THESIS_STUDENT_NONRES", sw("UUFA_LDR_THESIS_STUDENT_NONRES"),  "daily", "Daily Reports"),
    Rule("UUFA_ISIR_NOT_MATCH",            sw("UUFA_ISIR_NOT_MATCH"),             "daily", "Daily Reports"),
    Rule("ISIR_NO_MATCH",                  has("ISIR_NO_MATCH"),                  "daily", "Daily Reports"),
    Rule("IL_BLANK_ATB_PANEL",             has("IL_BLANK_ATB_PANEL"),             "daily", "Daily Reports"),
    Rule("IL_CMNT_CODE_NEED_RVW",          has("IL_CMNT_CODE_NEED_RVW"),          "daily", "Daily Reports"),
    Rule("UUFA_PELL_RSP_DSB_AWARD",        has("UUFA_PELL_RSP_DSB_AWARD"),        "pell",  "Pell Reports"),
    Rule("UUFA_PRCNT_USED_TOT_CHECK",      has("UUFA_PRCNT_USED_TOT_CHECK"),      "pell",  "Pell Reports"),
    Rule("UUFA_IL_COMBINED_NOPOST",        sw("UUFA_IL_COMBINED_NOPOST"),         "daily", "Daily Reports"),
    Rule("UUFA_IL_FA_DISB_NOT_MATCH_IA",   sw("UUFA_IL_FA_DISB_NOT_MATCH_IA"),    "daily", "Daily Reports"),

    # ── Monday Weekly Reports ──────────────────────────────────────────────
    Rule("UUFA_UOSFA_1690_LN_TYPES",       has("UUFA_UOSFA_1690_LN_TYPES"),       "weekly","Weekly Reports"),
    Rule("UUFA_WR_ACAD_LVLS_OUT_SYNC",     has("UUFA_WR_ACAD_LVLS_OUT_SYNC"),     "weekly","Weekly Reports"),
    Rule("UUFA_WR_ADV_FSOI_INITIATED",     has("UUFA_WR_ADV_FSOI_INITIATED"),     "weekly","Weekly Reports"),
    Rule("UUFA_WR_AGG_CK_MLT_YR_AWDED",   has("UUFA_WR_AGG_CK_MLT_YR_AWDED"),   "weekly","Weekly Reports"),
    Rule("UUFA_WR_AID_DISB_NO_ENR",        has("UUFA_WR_AID_DISB_NO_ENR"),        "weekly","Weekly Reports"),
    Rule("UUFA_WR_ALL_V4_V5_VER",          has("UUFA_WR_ALL_V4_V5_VER"),          "weekly","Weekly Reports"),
    Rule("UUFA_WR_AMERICORP_AWD_POST",     has("UUFA_WR_AMERICORP_AWD_POST"),     "weekly","Weekly Reports"),
    Rule("UUFA_WR_ATHLETE_NOT_DISB",       has("UUFA_WR_ATHLETE_NOT_DISB"),       "weekly","Weekly Reports"),
    Rule("UUFA_WR_ATH_HRS_AFTR_CENSUS",   has("UUFA_WR_ATH_HRS_AFTR_CENSUS"),   "weekly","Weekly Reports"),
    Rule("UUFA_WR_ATH_SF_TERM_BALANCE",    has("UUFA_WR_ATH_SF_TERM_BALANCE"),    "weekly","Weekly Reports"),
    Rule("UUFA_WR_AUDIT_CLSS_AID_DISB",   has("UUFA_WR_AUDIT_CLSS_AID_DISB"),   "weekly","Weekly Reports"),
    Rule("UUFA_WR_ISA_PER_TERM",           has("UUFA_WR_ISA_PER_TERM"),           "weekly","Weekly Reports"),
    Rule("UUFA_WR_AWD_UG_NOW_GRAD",        has("UUFA_WR_AWD_UG_NOW_GRAD"),        "weekly","Weekly Reports"),
    Rule("UUFA_WR_CHKLST_STATUS_ERROR",    has("UUFA_WR_CHKLST_STATUS_ERROR"),    "weekly","Weekly Reports"),
    Rule("UUFA_WR_CMT_CDE_O_AGR_LMT_2",   has("UUFA_WR_CMT_CDE_O_AGR_LMT_2"),   "weekly","Weekly Reports"),
    Rule("UUFA_WR_DISB_ATH_FAILURE",       has("UUFA_WR_DISB_ATH_FAILURE"),       "disb_failure","Weekly Reports"),
    Rule("UUFA_WR_DL_DISBURSED_LTHT",      has("UUFA_WR_DL_DISBURSED_LTHT"),      "weekly","Weekly Reports"),
    Rule("UUFA_WR_DL_EC_SUSPENDED",        has("UUFA_WR_DL_EC_SUSPENDED"),        "weekly","Weekly Reports"),
    Rule("_WR_DL_ORIG_TRNS_PEND",          has("_WR_DL_ORIG_TRNS_PEND"),          "weekly","Weekly Reports"),
    Rule("_WR_EFT_CONSENT_VERIF",          has("_WR_EFT_CONSENT_VERIF"),          "weekly","Weekly Reports"),
    Rule("_WR_FAFSA_CKLST_INCMP",          has("_WR_FAFSA_CKLST_INCMP"),          "weekly","Weekly Reports"),
    Rule("_WR_FALL_TOTAL_WDRN_DRP",        has("_WR_FALL_TOTAL_WDRN_DRP"),        "weekly","Weekly Reports"),
    Rule("_WR_SPR_TOTAL_WDRN_DRP",         has("_WR_SPR_TOTAL_WDRN_DRP"),         "weekly","Weekly Reports"),
    Rule("WR_SNGDO_CAMPUS",                has("WR_SNGDO_CAMPUS"),                "weekly","Weekly Reports"),
    Rule("_WR_SUM_TOTAL_WDRN_DRP",         has("_WR_SUM_TOTAL_WDRN_DRP"),         "weekly","Weekly Reports"),
    Rule("_WR_FARC_CHECKLIST",             has("_WR_FARC_CHECKLIST"),             "weekly","Weekly Reports"),
    Rule("_WR_FARC_CMNT_CODES",            has("_WR_FARC_CMNT_CODES"),            "weekly","Weekly Reports"),
    Rule("_WR_FED_AID_OVERAWARD",          has("_WR_FED_AID_OVERAWARD"),          "weekly","Weekly Reports"),
    Rule("_WR_FGED_ISIR_DEGREE",           has("_WR_FGED_ISIR_DEGREE"),           "weekly","Weekly Reports"),
    Rule("_WR_FPEL_INITIATED_AWDED",       has_all("_WR_FPEL","_INITIATED_AWDED"),"weekly","Weekly Reports"),
    Rule("WR_FREV_GR_WS",                  has("WR_FREV_GR_WS"),                  "weekly","Weekly Reports"),
    Rule("_WR_GENDER",                     has("_WR_GENDER"),                     "weekly","Weekly Reports"),
    Rule("_WR_HEDU_PARAMEDIC",             has("_WR_HEDU_PARAMEDIC"),             "weekly","Weekly Reports"),
    Rule("R_HOME_SCHOOLED",                has("R_HOME_SCHOOLED"),                "weekly","Weekly Reports"),
    Rule("_WR_HRS_DECREASE",               has("_WR_HRS_DECREASE"),               "weekly","Weekly Reports"),
    Rule("_WR_FHST_I_HST_COMPLETE",        has("_WR_FHST_I_HST_COMPLETE"),        "weekly","Weekly Reports"),
    Rule("_WR_ISIR_AS_EFC",                has("_WR_ISIR_AS_EFC"),                "weekly","Weekly Reports"),
    Rule("_WR_ISIR_COR_ASSESSMENT",        has("_WR_ISIR_COR_ASSESSMENT"),        "weekly","Weekly Reports"),
    Rule("_WR_ISIR_CORR_REJECT",           has("_WR_ISIR_CORR_REJECT"),           "weekly","Weekly Reports"),
    Rule("_WR_ISIR_DGR_ANSW_CHNG",         has("_WR_ISIR_DGR_ANSW_CHNG"),         "weekly","Weekly Reports"),
    Rule("_WR_ISIR_DEP_STAT_PRB",          has("_WR_ISIR_DEP_STAT_PRB"),          "weekly","Weekly Reports"),
    Rule("_WR_ISIR_REJECTED_CORR",         has("_WR_ISIR_REJECTED_CORR"),         "weekly","Weekly Reports"),
    Rule("UUFA_WR_ISIR_REJECT_CODES",      has("UUFA_WR_ISIR_REJECT_CODES"),      "weekly","Weekly Reports"),
    Rule("_WR_ISIR_SS_MCH_NOT_CON",        has("_WR_ISIR_SS_MCH_NOT_CON"),        "weekly","Weekly Reports"),
    Rule("_WR_ISIR_SUSPENSE",              has("_WR_ISIR_SUSPENSE"),              "weekly","Weekly Reports"),
    Rule("_WR_LEGAL_ALIEN_WORK",           has("_WR_LEGAL_ALIEN_WORK"),           "weekly","Weekly Reports"),
    Rule("_WR_LN_ACCPT_STAF_31_32",        has("_WR_LN_ACCPT_STAF_31_32"),        "weekly","Weekly Reports"),
    Rule("_WR_LOAN_CENSUS_DATE",           has("_WR_LOAN_CENSUS_DATE"),           "weekly","Weekly Reports"),
    Rule("_WR_LN_FA907",                   has("_WR_LN_FA907"),                   "weekly","Weekly Reports"),
    Rule("R_LOAN_ORIG_DEPT_REVIEW",        has("R_LOAN_ORIG_DEPT_REVIEW"),        "weekly","Weekly Reports"),
    Rule("_WR_LN_SENT_NO_RESPONSE",        has("_WR_LN_SENT_NO_RESPONSE"),        "weekly","Weekly Reports"),
    Rule("_WR_LOAN_TRANSMIT_HOLD",         has("_WR_LOAN_TRANSMIT_HOLD"),         "weekly","Weekly Reports"),
    Rule("_WR_LW_MD_DN_AW_NO_DISB",        has("_WR_LW_MD_DN_AW_NO_DISB"),        "weekly","Weekly Reports"),
    Rule("_WR_MNTGMR_AMCORP_OVRAW",        has("_WR_MNTGMR_AMCORP_OVRAW"),        "weekly","Weekly Reports"),
    Rule("_WR_MULTIPLE_EMPLIDS",           has("_WR_MULTIPLE_EMPLIDS"),           "weekly","Weekly Reports"),
    Rule("_WR_NO_COMMENT_CODE",            has("_WR_NO_COMMENT_CODE"),            "weekly","Weekly Reports"),
    Rule("_WR_NSLDS_LOAN_DATA",            has("_WR_NSLDS_LOAN_DATA"),            "weekly","Weekly Reports"),
    Rule("_WR_OVRD_ACAD_LVL",              has("_WR_OVRD_ACAD_LVL"),              "weekly","Weekly Reports"),
    Rule("_WR_PA_EXPECT",                  has("_WR_PA_EXPECT"),                  "weekly","Weekly Reports"),
    Rule("_WR_PA_FDEG_CHECKLIST",          has("_WR_PA_FDEG_CHECKLIST"),          "weekly","Weekly Reports"),
    Rule("_WR_PELL_AWRD_LOCK",             has("_WR_PELL_AWRD_LOCK"),             "weekly","Weekly Reports"),
    Rule("_WR_PELL_OVERPAYMENT",           has("_WR_PELL_OVERPAYMENT"),           "weekly","Weekly Reports"),
    Rule("_WR_PELL_SUMMER",                has("_WR_PELL_SUMMER"),                "weekly","Weekly Reports"),
    Rule("WR_PELL_SUMMER_AGGS",            has("WR_PELL_SUMMER_AGGS"),            "weekly","Weekly Reports"),
    Rule("_WR_PELL_TERM",                  has("_WR_PELL_TERM"),                  "weekly","Weekly Reports"),
    Rule("_WR_PERK_SPLIT_MISMATCH",        has("_WR_PERK_SPLIT_MISMATCH"),        "weekly","Weekly Reports"),
    Rule("_WR_PRK_LN_ACAD_LVL_CHG",        has("_WR_PRK_LN_ACAD_LVL_CHG"),        "weekly","Weekly Reports"),
    Rule("_WR_QUALITY_ASSURANCE",          has("_WR_QUALITY_ASSURANCE"),          "weekly","Weekly Reports"),
    Rule("R_RT4_DROPPED_CLASSES",          has("R_RT4_DROPPED_CLASSES"),          "weekly","Weekly Reports"),
    Rule("_WR_SCH_NOT_DISB",               has("_WR_SCH_NOT_DISB"),               "weekly","Weekly Reports"),
    Rule("_WR_SCHOLAR_TBP_NO_AWRD",        has("_WR_SCHOLAR_TBP_NO_AWRD"),        "weekly","Weekly Reports"),
    Rule("_WR_GRAD_FELLOW",                has("_WR_GRAD_FELLOW"),                "weekly","Weekly Reports"),
    Rule("_WR_SSR_MATCH_NOT_CNFRM",        has("_WR_SSR_MATCH_NOT_CNFRM"),        "weekly","Weekly Reports"),
    Rule("_WR_SSR_NOT_CNFRMD_VTRN",        has("_WR_SSR_NOT_CNFRMD_VTRN"),        "weekly","Weekly Reports"),
    Rule("_WR_SS_DB_OVERRIDE",             has("_WR_SS_DB_OVERRIDE"),             "weekly","Weekly Reports"),
    Rule("_WR_SUB_ISIR",                   has("_WR_SUB_ISIR"),                   "weekly","Weekly Reports"),
    Rule("_WR_SUMMER_NO_DL",               has("_WR_SUMMER_NO_DL"),               "weekly","Weekly Reports"),
    Rule("_WR_SUMMER_PELL_LTHT",           has("_WR_SUMMER_PELL_LTHT"),           "weekly","Weekly Reports"),
    Rule("_WR_SSP_DOB_PRB_APPLCNT",        has("_WR_SSP_DOB_PRB_APPLCNT"),        "weekly","Weekly Reports"),
    Rule("_WR_SSP_NAME_PRB_APLCNT",        has("_WR_SSP_NAME_PRB_APLCNT"),        "weekly","Weekly Reports"),
    Rule("_WR_SSP_SSN_PRB_APLCNT",         has("_WR_SSP_SSN_PRB_APLCNT"),         "weekly","Weekly Reports"),
    Rule("_WR_TERM_NSLDS_LOAN_YR",         has("_WR_TERM_NSLDS_LOAN_YR"),         "weekly","Weekly Reports"),
    Rule("_WR_TITLE_VII_MED_LOANS",        has("_WR_TITLE_VII_MED_LOANS"),        "weekly","Weekly Reports"),
    Rule("_WR_TRANSFER",                   has("_WR_TRANSFER"),                   "weekly","Weekly Reports"),
    Rule("_WR_UG_GR_DIR_LN_GR_TRM",        has("_WR_UG_GR_DIR_LN_GR_TRM"),        "weekly","Weekly Reports"),
    Rule("_WR_UG_GR_PLUS_GR_TERM",         has("_WR_UG_GR_PLUS_GR_TERM"),         "weekly","Weekly Reports"),
    Rule("WR_UAC_FASI_STATUS",             has("WR_UAC_FASI_STATUS"),             "weekly","Weekly Reports"),
    Rule("_WR_UAC_SNGDO",                  has("_WR_UAC_SNGDO"),                  "weekly","Weekly Reports"),
    Rule("_WR_UNDOCUMENTED_STUDENTS",      has("_WR_UNDOCUMENTED_STUDENTS"),      "weekly","Weekly Reports"),
    Rule("_WR_VERI_CHKLST_MISSING",        has("_WR_VERI_CHKLST_MISSING"),        "weekly","Weekly Reports"),
    Rule("_WR_VERI_INCOME_ADJ",            has("_WR_VERI_INCOME_ADJ"),            "weekly","Weekly Reports"),
    Rule("_WR_VER_NOT_CONSL",              has("_WR_VER_NOT_CONSL"),              "weekly","Weekly Reports"),
    Rule("_WR_VETERAN",                    has("_WR_VETERAN"),                    "weekly","Weekly Reports"),
    Rule("_WR_WEEKS_OF_INSTR_FIX",         has("_WR_WEEKS_OF_INSTR_FIX"),         "weekly","Weekly Reports"),
    Rule("_WR_DL_AY_SP_CANCELED",          has("_WR_DL_AY_SP_CANCELED"),          "weekly","Weekly Reports"),
    Rule("_WR_REJECT_CODE_ON_ISIR",        has("_WR_REJECT_CODE_ON_ISIR"),        "weekly","Weekly Reports"),
    Rule("_WR_RT4_FA_DROP_CLASSES",        has("_WR_RT4_FA_DROP_CLASSES"),        "weekly","Weekly Reports"),
    Rule("WR_AWARDS_OTHER_INST",           has("WR_AWARDS_OTHER_INST"),           "weekly","Weekly Reports"),
    Rule("WR_DEP_PRNT_SSN_RVW",            has("WR_DEP_PRNT_SSN_RVW"),            "weekly","Weekly Reports"),
    Rule("WR_DN_LW_MD_AID_ATRB",           has("WR_DN_LW_MD_AID_ATRB"),           "weekly","Weekly Reports"),
    Rule("WR_FSEOG_NO_PELL",               has("WR_FSEOG_NO_PELL"),               "weekly","Weekly Reports"),
    Rule("WR_FT_CLASS_OVERRIDES",          has("WR_FT_CLASS_OVERRIDES"),          "weekly","Weekly Reports"),
    Rule("WR_GR_ACAD_LV_OUT_SYNC",         has("WR_GR_ACAD_LV_OUT_SYNC"),         "weekly","Weekly Reports"),
    Rule("WR_PELL_COA_DOUBLE",             has("WR_PELL_COA_DOUBLE"),             "weekly","Weekly Reports"),
    Rule("WR_PKG_AWD_NO_BDGT",             has("WR_PKG_AWD_NO_BDGT"),             "weekly","Weekly Reports"),
    Rule("WR_SCH_TUITION_FEES",            has("WR_SCH_TUITION_FEES"),            "weekly","Weekly Reports"),
    Rule("WR_SCHOL_GRAD_DATE",             has("WR_SCHOL_GRAD_DATE"),             "weekly","Weekly Reports"),
    Rule("_WR_STDNT_NOT_PACKAGED",         has("_WR_STDNT_NOT_PACKAGED"),         "weekly","Weekly Reports"),
    Rule("UUFA_WR_DSB_PLN_SPLT_CD_FD",    has("UUFA_WR_DSB_PLN_SPLT_CD_FD"),    "weekly","Weekly Reports"),
    Rule("UUFA_WR_PELL_ELG_NO_PELL",      has("UUFA_WR_PELL_ELG_NO_PELL"),      "weekly","Weekly Reports"),
    Rule("UUFA_WR_CTZN_IND_AWD_NO_LN",    has("UUFA_WR_CTZN_IND_AWD_NO_LN"),    "weekly","Weekly Reports"),
    Rule("WR_SAVE_CTZNSHIP_VER",           has("WR_SAVE_CTZNSHIP_VER"),           "save",  "Weekly Reports"),
    Rule("WR_ALL_C_FVRA_I_NO_COR",         has("WR_ALL_C_FVRA_I_NO_COR"),         "save",  "Weekly Reports"),
    Rule("WR_CORRECTION_NOT_SENT",         has("WR_CORRECTION_NOT_SENT"),         "save",  "Weekly Reports"),
    Rule("UUFA_WR_WITH_COMMENT_CODE",      has("UUFA_WR_WITH_COMMENT_CODE"),      "save",  "Weekly Reports"),
    Rule("UUFA_WR_BLANK_LOAN_TYPE",        has("UUFA_WR_BLANK_LOAN_TYPE"),        "save",  "Weekly Reports"),
    Rule("UUFA_WR_TSM_ALERTS",             has("UUFA_WR_TSM_ALERTS"),             "weekly","Weekly Reports"),
    Rule("_WR_LOAN_EFT_DETAIL_ERROR",      has("_WR_LOAN_EFT_DETAIL_ERROR"),      "weekly","Weekly Reports"),
    Rule("_WR_NSL_PROMISSORY_NOTE",        has("_WR_NSL_PROMISSORY_NOTE"),        "weekly","Weekly Reports"),
    Rule("UUFA_AP_RPKG_FPEL_AWARD_LCK",   has("UUFA_AP_RPKG_FPEL_AWARD_LCK"),   "weekly","Weekly Reports"),
    Rule("_WR_FAVR_I_NO_FCOR_ALL_C",       has("_WR_FAVR_I_NO_FCOR_ALL_C"),       "weekly","Weekly Reports"),
    Rule("UUFA_SCHADM_DUALCAR",            has("UUFA_SCHADM_DUALCAR"),            "ea",    "Weekly Reports"),
    Rule("UUFA_WR_DEFERMENT_REPORT",       has("UUFA_WR_DEFERMENT_REPORT"),       "weekly","Weekly Reports"),
    Rule("UUFA_WR_BDGT_LN_FEE_MNL",       has("UUFA_WR_BDGT_LN_FEE_MNL"),       "weekly","Weekly Reports"),
    Rule("UUFA_WR_RESIDENCY_RECLASS",      has("UUFA_WR_RESIDENCY_RECLASS"),      "weekly","Weekly Reports"),
    Rule("UUFA_WR_SCH_PLACEHOLDER",        has("UUFA_WR_SCH_PLACEHOLDER"),        "weekly","Weekly Reports"),
    Rule("UUFA_WR_OUTSIDE_RESOURCES",      has("UUFA_WR_OUTSIDE_RESOURCES"),      "weekly","Weekly Reports"),
    Rule("UUFA_WR_PRO_STDNT_NOT_PACK",     has("UUFA_WR_PRO_STDNT_NOT_PACK"),     "weekly","Weekly Reports"),
    Rule("UUFA_WR_PHARM_ENRL_W_LOAN",      has("UUFA_WR_PHARM_ENRL_W_LOAN"),      "weekly","Weekly Reports"),
    # Packaging queries run manually on Mondays
    Rule("PRT_ATH_ACCEPT_FED_AID (WR)",    has("PRT_ATH_ACCEPT_FED_AID"),         "packaging","Packaging Reports"),
    Rule("PRT_ATH_AWD_CBA_GRANT (WR)",     has("PRT_ATH_AWD_CBA_GRANT"),          "packaging","Packaging Reports"),
    Rule("PRT_ATHLETE_GRAD_DATE (WR)",     has("PRT_ATHLETE_GRAD_DATE"),          "packaging","Packaging Reports"),
    Rule("PRT_ATH_OFFERED_FED_AID (WR)",   has("PRT_ATH_OFFERED_FED_AID"),        "packaging","Packaging Reports"),

    # ── Budget Reports ────────────────────────────────────────────────────
    Rule("UUFA_BR_ACAD_LVLS_OUT_SYNC",     sw("UUFA_BR_ACAD_LVLS_OUT_SYNC"),      "budget","Budget Reports"),
    Rule("UUFA_BR_ATH_TUIT_INCR",          sw("UUFA_BR_ATH_TUIT_INCR"),           "budget","Budget Reports"),
    Rule("_BR_BDGT_DOUBLE_BUDGETS",        has("_BR_BDGT_DOUBLE_BUDGETS"),        "budget","Budget Reports"),
    Rule("UUFA_BR_COA_LESS_HT",            sw("UUFA_BR_COA_LESS_HT"),             "budget","Budget Reports"),
    Rule("UUFA_BR_COA_TUIT_ZERO",          sw("UUFA_BR_COA_TUIT_ZERO"),           "budget","Budget Reports"),
    Rule("UUFA_BR_DN_LW_MD_AID_ATRB",      sw("UUFA_BR_DN_LW_MD_AID_ATRB"),       "budget","Budget Reports"),
    Rule("UUFA_BR_FT_CLASS_OVERRIDES",     sw("UUFA_BR_FT_CLASS_OVERRIDES"),      "budget","Budget Reports"),
    Rule("UUFA_BR_COA_ISIR_BDGT_DIFF",     sw("UUFA_BR_COA_ISIR_BDGT_DIFF"),      "budget","Budget Reports"),
    Rule("UUFA_BR_NO_BUDGET_ATTEND",       sw("UUFA_BR_NO_BUDGET_ATTEND"),        "budget","Budget Reports"),
    Rule("BR_PELL_COA_CHECK",              has("BR_PELL_COA_CHECK"),              "budget","Budget Reports"),
    Rule("UUFA_BR_PELL_COA_DOUBLE",        sw("UUFA_BR_PELL_COA_DOUBLE"),         "budget","Budget Reports"),
    Rule("BR_PELL_COA_DBLD_WRNG",          has("BR_PELL_COA_DBLD_WRNG"),          "budget","Budget Reports"),
    Rule("FA_BR_PELL_COA_LESS_HT_20",      sw("FA_BR_PELL_COA_LESS_HT_20"),       "budget","Budget Reports"),
    Rule("UUFA_BR_PROC_STAT_RVW_STAT",     sw("UUFA_BR_PROC_STAT_RVW_STAT"),      "budget","Budget Reports"),
    Rule("UUFA_BR_RES_NON_RES_BDGT",       sw("UUFA_BR_RES_NON_RES_BDGT"),        "budget","Budget Reports"),
    Rule("UUFA_BR_SCH_TUITION",            sw("UUFA_BR_SCH_TUITION"),             "budget","Budget Reports"),
    Rule("UUFA_BR_SCHOLAR_TUIT",           sw("UUFA_BR_SCHOLAR_TUIT"),            "budget","Budget Reports"),
    Rule("FA_BR_UFORM_CHANGE_BUD_DUR",     sw("FA_BR_UFORM_CHANGE_BUD_DUR"),      "budget","Budget Reports"),
    Rule("BR_ACAD_LVLS_NOT_SYNC",          has("BR_ACAD_LVLS_NOT_SYNC"),          "budget","Budget Reports"),
    Rule("UUFA_BR_COA_ONLINE",             has("UUFA_BR_COA_ONLINE"),             "budget","Budget Reports"),
    Rule("UUFA_BR_MANUAL_BDGT_NO_FEE",     sw("UUFA_BR_MANUAL_BDGT_NO_FEE"),      "budget","Budget Reports"),
    Rule("UUFA_USA_HRE_HOUSING",           sw("UUFA_USA_HRE_HOUSING"),            "budget","Budget Reports"),
    Rule("UUFA_HOUSING_CIS_UPDT",          sw("UUFA_HOUSING_CIS_UPDT"),           "budget","Budget Reports"),
    Rule("UUFA_BUDGETED_STDNT_INFO",       sw("UUFA_BUDGETED_STDNT_INFO"),        "budget","Budget Reports"),
    # Year-specific budget test queries
    Rule("UUFA_BUDGET_20YY",               sw_y("UUFA_BUDGET_20"),                "budget_wrong","Budget Reports"),

    # ── Packaging Reports ─────────────────────────────────────────────────
    Rule("UUFA_PRT_ACAD_LVLS_OUT_SYNC",    sw("UUFA_PRT_ACAD_LVLS_OUT_SYNC"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ACAD_PROG_REVIEW",      sw("UUFA_PRT_ACAD_PROG_REVIEW"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ATH_ACCEPT_FED_AID",    sw("UUFA_PRT_ATH_ACCEPT_FED_AID"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ATH_AWD_CBA_GRANT",     sw("UUFA_PRT_ATH_AWD_CBA_GRANT"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ATH_GRAD_DATE",         sw("UUFA_PRT_ATH_GRAD_DATE"),          "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ATH_OFFRD_FED_AID",     sw("UUFA_PRT_ATH_OFFRD_FED_AID"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ATH_OFFR_ACCPT_AID",    sw("UUFA_PRT_ATH_OFFR_ACCPT_AID"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_AWARD_TERM_HAD_SAP",    sw("UUFA_PRT_AWARD_TERM_HAD_SAP"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_AWARDS_OTHER_INST",     sw("UUFA_PRT_AWARDS_OTHER_INST"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_AWD_CMB_OVR_AG_RVW",   sw("UUFA_PRT_AWD_CMB_OVR_AG_RVW"),    "packaging","Packaging Reports"),
    Rule("FA_PRT_AWD_MASS_P_NO_AWARDS",    sw("FA_PRT_AWD_MASS_P_NO_AWARDS"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_AWD_PLL_ELG_NO_PLL",   sw("UUFA_PRT_AWD_PLL_ELG_NO_PLL"),    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_AWD_SUB_OVR_AG_RVW",   sw("UUFA_PRT_AWD_SUB_OVR_AG_RVW"),    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_CTZN_IND_AWD_NO_LN",   sw("UUFA_PRT_CTZN_IND_AWD_NO_LN"),    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_DEFR_ENROLLMENT",       sw("UUFA_PRT_DEFR_ENROLLMENT"),        "packaging","Packaging Reports"),
    Rule("UUFA_PRT_DEP_PRNT_SSN_RVW",      sw("UUFA_PRT_DEP_PRNT_SSN_RVW"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_DIAG_AWD_PELL_TERM",    sw("UUFA_PRT_DIAG_AWD_PELL_TERM"),     "packaging","Packaging Reports"),
    Rule("FA_PRT_DISB_PLAN_SPLT_CODE",     sw("FA_PRT_DISB_PLAN_SPLT_CODE"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_DL",                    sw("UUFA_PRT_DL"),                     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_DSB_PLN_SPLT_CD",      sw("UUFA_PRT_DSB_PLN_SPLT_CD"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_EXPECT_GRAD_TERM_11",   sw("UUFA_PRT_EXPECT_GRAD_TERM_11"),    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_GRAD_TRM",              sw("UUFA_PRT_GRAD_TRM"),               "packaging","Packaging Reports"),
    Rule("UUFA_PRT_HEAL",                  sw("UUFA_PRT_HEAL"),                   "packaging","Packaging Reports"),
    Rule("UUFA_PRT_LEU",                   sw("UUFA_PRT_LEU"),                    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_LN_CBA_AWD_NO_ELIG",   sw("UUFA_PRT_LN_CBA_AWD_NO_ELIG"),    "packaging","Packaging Reports"),
    Rule("UUFA_PRT_NSL_LOAN_RPT_VERI",     sw("UUFA_PRT_NSL_LOAN_RPT_VERI"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_NURSING_LOAN_RPT",      sw("UUFA_PRT_NURSING_LOAN_RPT"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_ON_LINE_PACKAGING",     sw("UUFA_PRT_ON_LINE_PACKAGING"),      "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PELL_COMMENT_037",      sw("UUFA_PRT_PELL_COMMENT_037"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PELL_ELG_NO_PELL",      sw("UUFA_PRT_PELL_ELG_NO_PELL"),       "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PLL_EL_CTZN_NOT_INDCT", sw("UUFA_PRT_PLL_EL_CTZN_NOT_INDCT"), "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PELL_UG_5TH_YR_2ND_BA", sw("UUFA_PRT_PELL_UG_5TH_YR_2ND_BA"), "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PHARM_NO_HEAL",         sw("UUFA_PRT_PHARM_NO_HEAL"),          "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PKG_AWD_NO_BDGT",       sw("UUFA_PRT_PKG_AWD_NO_BDGT"),        "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PKG_SCH_AWD_NO_BGT",    sw("UUFA_PRT_PKG_SCH_AWD_NO_BGT"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PRIOR_TERM_STFFRD_OFR", sw("UUFA_PRT_PRIOR_TERM_STFFRD_OFR"),  "packaging","Packaging Reports"),
    Rule("UUFA_PRT_SCHOL_GRAD_DATE",       sw("UUFA_PRT_SCHOL_GRAD_DATE"),        "packaging","Packaging Reports"),
    Rule("UUFA_PRT_SUB_UNSUB",             sw("UUFA_PRT_SUB_UNSUB"),              "packaging","Packaging Reports"),
    Rule("UUFA_PRT_SET_HEAL_FLAG",         sw("UUFA_PRT_SET_HEAL_FLAG"),          "packaging","Packaging Reports"),
    Rule("UUFA_PRT_STATE_OF_RES_FM_MH_PW", sw("UUFA_PRT_STATE_OF_RES_FM_MH_PW"),  "packaging","Packaging Reports"),
    Rule("FA_PRT_STILL_UNPRCD_AFTER_PKG",  sw("FA_PRT_STILL_UNPRCD_AFTER_PKG"),   "packaging","Packaging Reports"),
    Rule("UUFA_PRT_STDNT_NOT_PACKAGED",    sw("UUFA_PRT_STDNT_NOT_PACKAGED"),     "packaging","Packaging Reports"),
    Rule("UUFA_PRT_TEACH_CREDENTIAL",      sw("UUFA_PRT_TEACH_CREDENTIAL"),       "packaging","Packaging Reports"),
    Rule("PRT_SUB_UNSUB_FA_FA",            has("PRT_SUB_UNSUB_FA_FA"),            "packaging","Packaging Reports"),
    Rule("PRT_PELL_PKG_LOAD_CHCK",         has("PRT_PELL_PKG_LOAD_CHCK"),         "packaging","Packaging Reports"),
    Rule("PRT_COUNT_ITEM_TYPE",            has("PRT_COUNT_ITEM_TYPE"),            "packaging","Packaging Reports"),
    Rule("PKG_NOT_PKGD_NO_UNITS",          has("PKG_NOT_PKGD_NO_UNITS"),          "packaging","Packaging Reports"),
    Rule("UUFA_READY_PACKAGE",             sw("UUFA_READY_PACKAGE"),              "packaging","Packaging Reports"),
    Rule("UUFA_PRT_NO_FALL",               sw("UUFA_PRT_NO_FALL"),                "packaging","Packaging Reports"),
    Rule("UUFA_PRT_PELL_FPEL_INITIATED",   has_all("UUFA_PRT_PELL_FPEL","_INITIATED"),"packaging","Packaging Reports"),
    Rule("UUFA_READY_PKG",                 sw("UUFA_READY_PKG"),                  "packaging","Packaging Reports"),
    Rule("UUFA_RPKG_LVL",                  sw("UUFA_RPKG_LVL"),                   "packaging","Packaging Reports"),
    Rule("UUFA_PLACE_FA9",                 sw("UUFA_PLACE_FA9"),                  "packaging","Packaging Reports"),
    Rule("UUFA_PELL_LEU_450",              sw("UUFA_PELL_LEU_450"),               "packaging","Packaging Reports"),
    Rule("UUFA_BATCH_PKG_DETAIL",          sw("UUFA_BATCH_PKG_DETAIL"),           "packaging","Packaging Reports"),
    Rule("UUFA_PKG_SELECT",                sw("UUFA_PKG_SELECT"),                 "packaging","Packaging Reports"),

    # ── Monthly Reports ───────────────────────────────────────────────────
    Rule("MR_COMMENT_CODE_298",            has("MR_COMMENT_CODE_298"),            "monthly","Monthly Reports"),
    Rule("MR_3RD_PARTY_CROSSWALK",         has("MR_3RD_PARTY_CROSSWALK"),         "monthly","Monthly Reports"),
    Rule("MR_FDEGRX_FABCX_FBLKD_FDG",     has("MR_FDEGRX_FABCX_FBLKD_FDG"),     "monthly","Monthly Reports"),
    Rule("MR_3RD_PRT_MNTR_IA_ALL",         has("MR_3RD_PRT_MNTR_IA_ALL"),         "monthly","Monthly Reports"),
    Rule("MR_ACAD_LVLS_NOT_SYNC",          has("MR_ACAD_LVLS_NOT_SYNC"),          "monthly","Monthly Reports"),
    Rule("MR_ADM_DEFERRAL",                has("MR_ADM_DEFERRAL"),                "monthly","Monthly Reports"),
    Rule("MR_ALT_LN_TRNSMIT_HOLD",         has("MR_ALT_LN_TRNSMIT_HOLD"),         "monthly","Monthly Reports"),
    Rule("MR_ATHLETE_T53_AWARDS",          has("MR_ATHLETE_T53_AWARDS"),          "monthly","Monthly Reports"),
    Rule("MR_COD_DL",                      has("MR_COD_DL"),                      "monthly","Monthly Reports"),
    Rule("MR_COD_PELL_TEACH_IASG",         has("MR_COD_PELL_TEACH_IASG"),         "monthly","Monthly Reports"),
    Rule("MR_DIR_LN_TRNSMIT_HOLD",         has("MR_DIR_LN_TRNSMIT_HOLD"),         "monthly","Monthly Reports"),
    Rule("MR_DISB_ATH_AWD_NOPOST",         has("MR_DISB_ATH_AWD_NOPOST"),         "monthly","Monthly Reports"),
    Rule("MR_DL_DISB_FAILED",              has("MR_DL_DISB_FAILED"),              "monthly_dl","Monthly Reports"),
    Rule("MR_DL_ORIG_AWARD",               has("MR_DL_ORIG_AWARD"),               "monthly","Monthly Reports"),
    Rule("MR_DSB_CASH_AWD_NOPOST",         has("MR_DSB_CASH_AWD_NOPOST"),         "monthly","Monthly Reports"),
    Rule("MR_DSB_WAVR_AWD_NOPOST",         has("MR_DSB_WAVR_AWD_NOPOST"),         "monthly","Monthly Reports"),
    Rule("DSB_AWD_NOPOST",                 has("DSB_AWD_NOPOST"),                 "monthly","Monthly Reports"),
    Rule("MR_DN_INC_CHECKLISTS",           has("MR_DN_INC_CHECKLISTS"),           "monthly","Monthly Reports"),
    Rule("MR_M_L_D_INI_CHECKLIST",         has("MR_M_L_D_INI_CHECKLIST"),         "monthly","Monthly Reports"),
    Rule("MR_FWS_WITH_NSI_HOLD",           has("MR_FWS_WITH_NSI_HOLD"),           "monthly","Monthly Reports"),
    Rule("MR_GRAD_TERM_PRB",               has("MR_GRAD_TERM_PRB"),               "monthly","Monthly Reports"),
    Rule("MR_ITEM_CHARTFLD_SETUP",         has("MR_ITEM_CHARTFLD_SETUP"),         "monthly_acct","Monthly Reports"),
    Rule("MR_ITEM_TYPE_DISB_RULE",         has("MR_ITEM_TYPE_DISB_RULE"),         "monthly","Monthly Reports"),
    Rule("MR_LAW_INC_CHECKLISTS",          has("MR_LAW_INC_CHECKLISTS"),          "monthly","Monthly Reports"),
    Rule("MR_LOAN_AWD_PARTL_DISB",         has("MR_LOAN_AWD_PARTL_DISB"),         "monthly","Monthly Reports"),
    Rule("MR_MED_INC_CHECKLISTS",          has("MR_MED_INC_CHECKLISTS"),          "monthly","Monthly Reports"),
    Rule("MR_MED_LAW_LVL_REVIEW",          has("MR_MED_LAW_LVL_REVIEW"),          "monthly","Monthly Reports"),
    Rule("_MR_DN_LW_MD_LVL_RVW",           has("_MR_DN_LW_MD_LVL_RVW"),           "monthly","Monthly Reports"),
    Rule("MR_PART_TW_OTHER_SCH",           has("MR_PART_TW_OTHER_SCH"),           "monthly","Monthly Reports"),
    Rule("MR_PELL_AWD_ADJUSTMENT",         has("MR_PELL_AWD_ADJUSTMENT"),         "monthly","Monthly Reports"),
    Rule("MR_PELL_ONLY",                   has("MR_PELL_ONLY"),                   "monthly","Monthly Reports"),
    Rule("MR_PELL_SSN_MISMATCH",           has("MR_PELL_SSN_MISMATCH"),           "monthly","Monthly Reports"),
    Rule("MR_PERKINS_CLASS_LIMIT",         has("MR_PERKINS_CLASS_LIMIT"),         "monthly","Monthly Reports"),
    Rule("MR_PERK_MISC_LN",                has("MR_PERK_MISC_LN"),                "monthly","Monthly Reports"),
    Rule("_MR_SCH_IT_RECON",               has("_MR_SCH_IT_RECON"),               "monthly","Monthly Reports"),
    Rule("MR_SCH + LOA",                   has_all("MR_SCH","LOA"),               "monthly","Monthly Reports"),
    Rule("SCHOLAR_REINSTATE",              has("SCHOLAR_REINSTATE"),              "monthly","Monthly Reports"),
    Rule("MR_SF_DIS_AWD_PT_ER",            has("MR_SF_DIS_AWD_PT_ER"),            "monthly","Monthly Reports"),
    Rule("MR_STATE_FM_MH_PW",              has("MR_STATE_FM_MH_PW"),              "monthly","Monthly Reports"),
    Rule("MR_SUSPEND_RC2",                 has("MR_SUSPEND_RC2"),                 "monthly","Monthly Reports"),
    Rule("MR_UFORM_GRAD_TERM_PRB",         has("MR_UFORM_GRAD_TERM_PRB"),         "monthly","Monthly Reports"),
    Rule("MR_UNDS_OFFER_SCHOLAR",          has("MR_UNDS_OFFER_SCHOLAR"),          "monthly","Monthly Reports"),
    Rule("MR_UNDS_OFRD_AMT",               has("MR_UNDS_OFRD_AMT"),               "monthly","Monthly Reports"),
    Rule("MR_VERIFY_DEP_OVERRIDE",         has("MR_VERIFY_DEP_OVERRIDE"),         "monthly","Monthly Reports"),
    Rule("MR_GRBEN_EA_POST",               has("MR_GRBEN_EA_POST"),               "monthly","Monthly Reports"),
    Rule("SEFA_DL_TOTAL_AWARDS",           has("SEFA_DL_TOTAL_AWARDS"),           "monthly","Monthly Reports"),
    Rule("SEFA_TOTAL_STUDENT",             has("SEFA_TOTAL_STUDENT"),             "monthly","Monthly Reports"),
    Rule("STP_DISB_RULE_MISMATCH",         has("STP_DISB_RULE_MISMATCH"),         "monthly","Monthly Reports"),
    Rule("ussfa037 (Award Summary)",       has("ussfa037"),                       "monthly_award","Monthly Reports",
         rename_fn=_award_rename),
    Rule("ussfa035 (Award Summary)",       has("ussfa035-"),                      "monthly_award","Monthly Reports",
         rename_fn=_award_rename),
    Rule("MR_EXPIRED_MPN_CURR_LN",         has("MR_EXPIRED_MPN_CURR_LN"),         "monthly","Monthly Reports"),
    Rule("_MR_RNDM_GRAD_ENR_CHANG",        has("_MR_RNDM_GRAD_ENR_CHANG"),        "monthly","Monthly Reports"),
    Rule("UUFA_DL_COD_FYTD_AMOUNTS",       has("UUFA_DL_COD_FYTD_AMOUNTS"),       "monthly","Monthly Reports"),
    Rule("UUFA_SEFA_DL_TOTAL_STUDENT",     has("UUFA_SEFA_DL_TOTAL_STUDENT"),     "monthly","Monthly Reports"),
    Rule("UUFA_EXPECTED_GRAD_DATE_ERROR",  has("UUFA_EXPECTED_GRAD_DATE_ERROR"),  "monthly","Monthly Reports"),
    Rule("UUFA_STP_MISSING_DISB_RULES",    has("UUFA_STP_MISSING_DISB_RULES"),    "monthly","Monthly Reports"),
    Rule("UUFA_MR_FDEGRX_FABCX_FBLKD",    has("UUFA_MR_FDEGRX_FABCX_FBLKD"),    "monthly","Monthly Reports"),

    # ── Disbursement (uses disbursement date for rename) ──────────────────
    Rule("UUFA_DQ_AUTHORIZED_NOT_DISB",    sw("UUFA_DQ_AUTHORIZED_NOT_DISB"),     "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_ALL_DISBURSED",          sw("UUFA_DQ_ALL_DISBURSED"),           "disb", "Daily Reports", use_disb_date=True),
    Rule("FA_DQ_ATHLETE_RM_BD",            sw("FA_DQ_ATHLETE_RM_BD"),             "disb", "Daily Reports", use_disb_date=True),
    Rule("FA_DQ_ATH_OFF_SCHED_RM_BD",      sw("FA_DQ_ATH_OFF_SCHED_RM_BD"),       "disb", "Daily Reports", use_disb_date=True),
    Rule("_CASH_DISB_TOTALS",              has("_CASH_DISB_TOTALS"),              "disb", "Daily Reports", use_disb_date=True),
    Rule("_DQ_DISB_TOTALS",                has("_DQ_DISB_TOTALS"),                "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_FALL",                   sw("UUFA_DQ_FALL"),                    "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_SPRING",                 sw("UUFA_DQ_SPRING"),                  "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_DL_SUMMER",              sw("UUFA_DQ_DL_SUMMER"),               "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_UG_PLUS_REFUND_IA",      sw("UUFA_DQ_UG_PLUS_REFUND_IA"),       "disb", "Daily Reports", use_disb_date=True),
    Rule("DQ_MISC_CARES",                  has("DQ_MISC_CARES"),                  "disb", "Daily Reports", use_disb_date=True),
    Rule("MISC_DISB_TOTALS",               has("MISC_DISB_TOTALS"),               "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_MISC_RESOURCE_DISB",     sw("UUFA_DQ_MISC_RESOURCE_DISB"),      "disb", "Daily Reports", use_disb_date=True),
    Rule("NONCASH_DISB_TOTALS",            has("NONCASH_DISB_TOTALS"),            "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_PELL_ACPT_GR8_DISB",    sw("UUFA_DQ_PELL_ACPT_GR8_DISB"),     "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_SF_ITEM_TYPE_ERROR",     sw("UUFA_DQ_SF_ITEM_TYPE_ERROR"),      "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_TEACH_GRANT",            sw("UUFA_DQ_TEACH_GRANT"),             "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_DQ_DISB_BREAKDOWN",         sw("UUFA_DQ_DISB_BREAKDOWN"),          "disb", "Daily Reports", use_disb_date=True),
    Rule("UUFA_PELL_AID_APPL_STATUS",      has("UUFA_PELL_AID_APPL_STATUS"),      "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_COD_DISB_DETAIL",      has("UUFA_PELL_COD_DISB_DETAIL"),      "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_COD_DISB_ENTRY",       has("UUFA_PELL_COD_DISB_ENTRY"),       "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_COD_FYTD_AMOUNTS",     has("UUFA_PELL_COD_FYTD_AMOUNTS"),     "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_COD_PHOLD_RJCTD",      has("UUFA_PELL_COD_PHOLD_RJCTD"),      "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_COA_BLANK",            has("UUFA_PELL_COA_BLANK"),            "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_PRCSS_STAT_BLNK",      has("UUFA_PELL_PRCSS_STAT_BLNK"),      "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_RSP_COD_EDITS",        has("UUFA_PELL_RSP_COD_EDITS"),        "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_RSP_COD_IN",           has("UUFA_PELL_RSP_COD_IN"),           "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_RSP_DISB_ACTION_CODE", has("UUFA_PELL_RSP_DISB_ACTION_CODE"), "pell_disb","Pell Reports"),
    Rule("UUFA_PELL_RSP_ORIG_AWARD",       has("UUFA_PELL_RSP_ORIG_AWARD"),       "pell_disb","Pell Reports"),

    # ── SAP / End-of-Term (special rename strips trailing _NNN) ───────────
    Rule("UUFA_EOT_SAP_AGGCP_DLM",         sw("UUFA_EOT_SAP_AGGCP_DLM"),          "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_ACAD_PLAN_RVW_FRAP",    sw("UUFA_EOT_ACAD_PLAN_RVW_FRAP"),     "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_CBA_ACAD_PRG_BELOW_FT", sw("UUFA_EOT_CBA_ACAD_PRG_BELOW_FT"),  "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_CBA_UNDISBURSED",        sw("UUFA_EOT_CBA_UNDISBURSED"),         "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_ALT_LOAN_SAP",           sw("UUFA_EOT_ALT_LOAN_SAP"),            "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_LN_ORIG_FAIL_PENDING",   sw("UUFA_EOT_LN_ORIG_FAIL_PENDING"),    "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_LN_ACD_PRG_BLW_HT",     sw("UUFA_EOT_LN_ACD_PRG_BLW_HT"),      "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_PRO_STDNT_SAP_WARNING",  sw("UUFA_EOT_PRO_STDNT_SAP_WARNING"),   "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_MED_SAP",                sw("UUFA_EOT_MED_SAP"),                 "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_FWS_WITH_NSI_HOLD",      sw("UUFA_EOT_FWS_WITH_NSI_HOLD"),       "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_PELL",                   sw("UUFA_EOT_PELL"),                    "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_THESIS_STUDENT_NONRES",  sw("UUFA_EOT_THESIS_STUDENT_NONRES"),   "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_SCH_ACAD_PROG_REVIEW",   sw("UUFA_EOT_SCH_ACAD_PROG_REVIEW"),    "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_SAP_AGGCP",              sw("UUFA_EOT_SAP_AGGCP"),               "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_EU",                     sw("UUFA_EOT_EU"),                      "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_SAP_FSAP",               sw("UUFA_EOT_SAP_FSAP"),                "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("UUFA_EOT_SCHOLAR_LEADER_CGPA",    sw("UUFA_EOT_SCHOLAR_LEADER_CGPA"),     "sap", "SAP Reports", rename_fn=_eot_rename),
    Rule("EOT_WUE_ACAD_PROG_REV",           has("EOT_WUE_ACAD_PROG_REV"),           "sap", "SAP Reports", rename_fn=_eot_rename),

    # ── Direct Loan (triggers origination copy) ───────────────────────────
    Rule("DLOUT",                          has("DLOUT"),                           "dl",        "Direct Loan Reports", flag="dlout"),
    Rule("UUFA_DL_COD_EDITS",              sw("UUFA_DL_COD_EDITS"),               "dl_response","Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLO_PRORATION_ENROLL",      sw("UUFA_DLO_PRORATION_ENROLL"),       "dl_heal",   "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_ORIG_TRNS_PEND",        sw("UUFA_DLR_ORIG_TRNS_PEND"),         "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_ENTRANCE_COUNSEL",      sw("UUFA_DLR_ENTRANCE_COUNSEL"),       "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_EFT_DT_LNDR_ERR", sw("UUFA_DLR_LOAN_EFT_DT_LNDR_ERR"),  "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_ORIG_FA_LOAD",     sw("UUFA_DLR_LOAN_ORIG_FA_LOAD"),      "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_NO_NSLDS",         sw("UUFA_DLR_LOAN_NO_NSLDS"),          "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_ORIG_ACAD_LVL",    sw("UUFA_DLR_LOAN_ORIG_ACAD_LVL"),     "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_ORIG_EDIT_ERR",    sw("UUFA_DLR_LOAN_ORIG_EDIT_ERR"),     "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_ORIG_SPLT_CDS",    sw("UUFA_DLR_LOAN_ORIG_SPLT_CDS"),     "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("DLR_LN_ORIG_VLOAN_RSN",          has("DLR_LN_ORIG_VLOAN_RSN"),          "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_LOAN_SPC_NEED_OVWD",    sw("UUFA_DLR_LOAN_SPC_NEED_OVWD"),     "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("DLR_LN_ACPT_STAF_31_32",         has("DLR_LN_ACPT_STAF_31_32"),         "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_NOT_DISB",              sw("UUFA_DLR_NOT_DISB"),               "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_DLR_UG_PLUS_REFND_IND",     sw("UUFA_DLR_UG_PLUS_REFND_IND"),      "dl",        "Direct Loan Reports", flag="direct_loan"),
    Rule("UUFA_ADJUST_LOAN_DATES",         sw("UUFA_ADJUST_LOAN_DATES"),          "dl",        "Other Reports"),
    Rule("UUFA_IL_RPKG_DL_OFFERS",         sw("UUFA_IL_RPKG_DL_OFFERS"),          "dl",        "Other Reports"),

    # ── Alternative Loan (triggers origination copy) ───────────────────────
    Rule("UUFA_ALR_110_CHNG_PDG_TRANS",    sw("UUFA_ALR_110_CHNG_PDG_TRANS"),     "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_CL_APP_RSPNS_ERR",      sw("UUFA_ALR_CL_APP_RSPNS_ERR"),       "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALT_LN_AWRD_DISC",          sw("UUFA_ALT_LN_AWRD_DISC"),           "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALT_LN_NO_DISB",            sw("UUFA_ALT_LN_NO_DISB"),             "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LN_SENT_NO_RESP",       sw("UUFA_ALR_LN_SENT_NO_RESP"),        "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LN_EFT",                sw("UUFA_ALR_LN_EFT"),                 "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LOAN_ORIG",             sw("UUFA_ALR_LOAN_ORIG"),              "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LN_ORIG_EDIT_ERR",      sw("UUFA_ALR_LN_ORIG_EDIT_ERR"),       "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LOAN_ORG_LND_NT_CK",    sw("UUFA_ALR_LOAN_ORG_LND_NT_CK"),     "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALR_LOAN_SPC_NEED_OVWD",    sw("UUFA_ALR_LOAN_SPC_NEED_OVWD"),     "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALT_LOANS_RECIEVED_NO_SSN", sw("UUFA_ALT_LOANS_RECIEVED_NO_SSN"),  "alt_loan","Alternative Loan Reports", flag="alt_loan"),
    Rule("UUFA_ALT_LOANS_SSN_MATCH",       sw("UUFA_ALT_LOANS_SSN_MATCH"),        "alt_loan","Alternative Loan Reports", flag="alt_loan"),

    # ── Pre-Repackaging / Mid-Repack / After-Repack (all → Pell) ──────────
    Rule("UUFA_PP_RPKG_AGGREGATE_LIMITS",  sw("UUFA_PP_RPKG_AGGREGATE_LIMITS"),   "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_AWD_AY_NO_BDGT",    sw("UUFA_PP_RPKG_AWD_AY_NO_BDGT"),     "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_AWD_STRM_INACTIVE", sw("UUFA_PP_RPKG_AWD_STRM_INACTIVE"),  "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_AWRD_LOCK",         sw("UUFA_PP_RPKG_AWRD_LOCK"),          "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_COA_DOUBLE",        sw("UUFA_PP_RPKG_COA_DOUBLE"),         "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_LTHT_PELL_COA",     sw("UUFA_PP_RPKG_LTHT_PELL_COA"),      "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_RPKG_NO_BUDGET",    sw("UUFA_PP_RPKG_RPKG_NO_BUDGET"),     "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_RPKG_SNAPSHOT",     sw("UUFA_PP_RPKG_RPKG_SNAPSHOT"),      "pell", "Pell Reports"),
    Rule("UUFA_PP_RPKG_TOTAL_WDRN_DRP",    sw("UUFA_PP_RPKG_TOTAL_WDRN_DRP"),     "pell", "Pell Reports"),
    Rule("UUFA_READY_REPACKAGE",           sw("UUFA_READY_REPACKAGE"),            "pell", "Pell Reports"),
    Rule("UUFA_MP_RPKG",                   sw("UUFA_MP_RPKG"),                    "pell", "Pell Reports"),
    Rule("UUFA_AP_RPKG",                   sw("UUFA_AP_RPKG"),                    "pell", "Pell Reports"),

    # ── Daily Scholarships ────────────────────────────────────────────────
    Rule("UUFA_SCHOLAR_DISB_ZERO",         sw("UUFA_SCHOLAR_DISB_ZERO"),          "scholar_daily","Scholarship Reports"),
    Rule("UUFA_SCHOLAR_TWO_CAREERS",       sw("UUFA_SCHOLAR_TWO_CAREERS"),        "scholar_daily","Scholarship Reports"),
    Rule("UUFA_SCHOLAR_AUTH_NOT_DISB",     sw("UUFA_SCHOLAR_AUTH_NOT_DISB"),      "scholar_daily","Scholarship Reports"),
    Rule("BOOKS_NOPOST",                   has("BOOKS_NOPOST"),                   "scholar_save","Scholarship Reports"),
    Rule("MISC_NOPOST",                    has("MISC_NOPOST"),                    "scholar_save","Scholarship Reports"),
    Rule("ROOMBOARD_NOPOST",               has("ROOMBOARD_NOPOST"),               "scholar_save","Scholarship Reports"),
    Rule("TRAINEESHIP_NOPOST",             has("TRAINEESHIP_NOPOST"),             "scholar_save","Scholarship Reports"),
    Rule("TRAVEL_NOPOST",                  has("TRAVEL_NOPOST"),                  "scholar_save","Scholarship Reports"),
    Rule("IL_FELLOWSHIP_SCH_NP",           has("IL_FELLOWSHIP_SCH_NP"),           "scholar_daily","Scholarship Reports"),

    # ── Weekly Scholarships ───────────────────────────────────────────────
    Rule("DEPT_POST_WRNG_ITEM",            has("DEPT_POST_WRNG_ITEM"),            "scholar_weekly","Scholarship Reports"),
    Rule("MISC_TOTAL",                     has("MISC_TOTAL"),                     "scholar_save", "Scholarship Reports"),
    Rule("CARES_HEERF",                    has("CARES_HEERF"),                    "scholar_weekly","Scholarship Reports"),
    Rule("BOOKS_TOTAL",                    has("BOOKS_TOTAL"),                    "scholar_save", "Scholarship Reports"),
    Rule("ROOMBOARD_TOTAL",                has("ROOMBOARD_TOTAL"),                "scholar_save", "Scholarship Reports"),
    Rule("TRAVEL_TOTAL",                   has("TRAVEL_TOTAL"),                   "scholar_save", "Scholarship Reports"),
    Rule("TRAINEESHIP + TOTAL",            has_all("TRAINEESHIP","TOTAL"),        "scholar_save", "Scholarship Reports"),
    Rule("SCH_ALL_NEED",                   has("SCH_ALL_NEED"),                   "scholar_weekly","Scholarship Reports"),
    Rule("SCH_ALL_NRFRESH",                has("SCH_ALL_NRFRESH"),                "scholar_weekly","Scholarship Reports"),
    Rule("SCH_ALL_NRTRAN",                 has("SCH_ALL_NRTRAN"),                 "scholar_weekly","Scholarship Reports"),
    Rule("SCH_ALL_RESFRESH",               has("SCH_ALL_RESFRESH"),               "scholar_weekly","Scholarship Reports"),
    Rule("SCH_ALL_RESTRAN",                has("SCH_ALL_RESTRAN"),                "scholar_weekly","Scholarship Reports"),
    Rule("WS_UT_PROMISE_CHKLST",           has("WS_UT_PROMISE_CHKLST"),           "scholar_weekly","Scholarship Reports"),
    Rule("WS_SCH_ALL_EA_ERRORS",           has("WS_SCH_ALL_EA_ERRORS"),           "scholar_errors","External Award Reports"),
    Rule("WS_SCHOLAR_ADM_REVIEW",          has("WS_SCHOLAR_ADM_REVIEW"),          "scholar_weekly","Scholarship Reports"),
    Rule("WS_FAC_STAFF",                   has("WS_FAC_STAFF"),                   "scholar_weekly","Scholarship Reports"),
    Rule("WS_SCHOLAR_STATUS",              has("WS_SCHOLAR_STATUS"),              "scholar_weekly","Scholarship Reports"),
    Rule("UUFA_IL_FELLOWSHIP_SCH_NOPOST",  has("UUFA_IL_FELLOWSHIP_SCH_NOPOST"),  "scholar_weekly","Scholarship Reports"),

    # ── 2nd LDR / Day-after-LDR ───────────────────────────────────────────
    Rule("UUFA_CBA_UNDISBURSED",           sw("UUFA_CBA_UNDISBURSED"),            "term", "Financial Aid Reports"),
    Rule("UUFA_HRS_DECREASE",              sw("UUFA_HRS_DECREASE"),               "term", "Financial Aid Reports"),
    Rule("UUFA_PELL_ELIG_ENROLL_NO_AWARD", sw("UUFA_PELL_ELIG_ENROLL_NO_AWARD"),  "term", "Financial Aid Reports"),
    Rule("UUFA_PELL_OFFERED_NOT_DISB",     sw("UUFA_PELL_OFFERED_NOT_DISB"),      "term", "Financial Aid Reports"),
    Rule("UUFA_PELL_DL_MATH990",           sw("UUFA_PELL_DL_MATH990"),            "term", "Financial Aid Reports"),
    Rule("PELL_DL_MATH980",                has("PELL_DL_MATH980"),                "term", "Financial Aid Reports"),
    Rule("UUFA_PELL_DL_ELI575_ELI685",     sw("UUFA_PELL_DL_ELI575_ELI685"),      "term", "Financial Aid Reports"),
    Rule("UUFA_SF_DISB_ATH_AWD_NOPOST",    sw("UUFA_SF_DISB_ATH_AWD_NOPOST"),     "term", "Financial Aid Reports"),
    Rule("UUFA_SF_DISB_WAIVER_AWD_NOPOST", sw("UUFA_SF_DISB_WAIVER_AWD_NOPOST"),  "term", "Financial Aid Reports"),
    Rule("UUFA_PELL_TERM_AWARDS",          sw("UUFA_PELL_TERM_AWARDS"),           "ldr",  "Financial Aid Reports"),
    Rule("UUFA_LDR_MIN_ENROLLMENT",        sw("UUFA_LDR_MIN_ENROLLMENT"),         "ldr",  "Financial Aid Reports"),
    Rule("UUFA_LDR_MINIMUM_ENROLLMENT",    sw("UUFA_LDR_MINIMUM_ENROLLMENT"),     "ldr",  "Financial Aid Reports"),
    Rule("UUFA_LDR_PELL_AWARDS",           sw("UUFA_LDR_PELL_AWARDS"),            "ldr",  "Financial Aid Reports"),
    Rule("UUFA_ATHLETE_AWARD_DISBURSED",   sw("UUFA_ATHLETE_AWARD_DISBURSED"),    "ldr",  "Financial Aid Reports"),
    Rule("UUFA_PELL_SUMMER_ENROLLMENT",    sw("UUFA_PELL_SUMMER_ENROLLMENT"),     "ldr",  "Financial Aid Reports"),
    Rule("UUFA_THESIS_STUDENTS_NONRES",    sw("UUFA_THESIS_STUDENTS_NONRES"),     "ldr",  "Financial Aid Reports"),
    Rule("UUFA_REGISTERED_CENSUS_DATE",    sw("UUFA_REGISTERED_CENSUS_DATE"),     "ldr",  "Financial Aid Reports"),
    Rule("UUFA_NO_MTRC_STU_ATH_BAL_OWING", sw("UUFA_NO_MTRC_STU_ATH_BAL_OWING"),  "ldr",  "Financial Aid Reports"),
    Rule("UUFA_FATERM_SOURCE_N_AWD_ATH",   sw("UUFA_FATERM_SOURCE_N_AWD_ATH"),    "ldr",  "Financial Aid Reports"),
    Rule("UUFA_FATERM_SOURCE_N_AWD_SV",    sw("UUFA_FATERM_SOURCE_N_AWD_SV"),     "ldr",  "Financial Aid Reports"),
    Rule("UUFA_ATH_NO_MTRC_STU_BAL_OWING", sw("UUFA_ATH_NO_MTRC_STU_BAL_OWING"),  "ldr",  "Financial Aid Reports"),
    Rule("UUFA_PRT_AWD_PLL_ELG_NO_PLL",   sw("UUFA_PRT_AWD_PLL_ELG_NO_PLL"),    "ldr",  "Financial Aid Reports"),

    # ── ATB / FBill / 3C ──────────────────────────────────────────────────
    Rule("UUFA_ADD_F",                     sw("UUFA_ADD_F"),                      "3c",   "Daily Reports"),
    Rule("UUFA_COMPLETE_F",                sw("UUFA_COMPLETE_F"),                 "3c",   "Daily Reports"),
    Rule("UUFA_HS_06_AFTER",               sw("UUFA_HS_06_AFTER"),               "atb",  "Daily Reports"),
    Rule("UUFA_HS_04_AFTER",               sw("UUFA_HS_04_AFTER"),               "atb",  "Daily Reports"),
    Rule("UUFA_GED_07_AFTER",              sw("UUFA_GED_07_AFTER"),              "atb",  "Daily Reports"),
    Rule("UUFA_ATB_ISIR_NOT_MATCH",        has("UUFA_ATB_ISIR_NOT_MATCH"),        "atb",  "Daily Reports"),
    Rule("UUFA_ATB_SEQUENCE_DIFF",         sw("UUFA_ATB_SEQUENCE_DIFF"),          "atb",  "Daily Reports"),

    # ── TSM ────────────────────────────────────────────────────────────────
    Rule("NSLDS_REQUEST",                  has("NSLDS_REQUEST"),                  "tsm",  "Financial Aid Reports"),
    Rule("_NSLDS_VAR_FLAG9",               has("_NSLDS_VAR_FLAG9"),               "tsm",  "Financial Aid Reports"),
    Rule("UUFA_ALERT_TSM_REVIEW_NSLDS",    has("UUFA_ALERT_TSM_REVIEW_NSLDS"),    "tsm",  "Financial Aid Reports"),
    Rule("UUFA_ALERT_TSM_SUSPEND",         has("UUFA_ALERT_TSM_SUSPEND"),         "tsm",  "Financial Aid Reports"),

    # ── Dashboard Files (archived with date; saved to UOSFA without date, overwrite) ──
    Rule("UUFA_DB_PACKAGING_SUMMARY",     sw("UUFA_DB_PACKAGING_SUMMARY"),     "dashboard", "UUFA_DB_PACKAGING_SUMMARY",     uosfa_name_fn=_db_uosfa_name, overwrite=True),
    Rule("UUFA_DB_PACKAGING_AMOUNTS",     sw("UUFA_DB_PACKAGING_AMOUNTS"),     "dashboard", "UUFA_DB_PACKAGING_AMOUNTS",     uosfa_name_fn=_db_uosfa_name, overwrite=True),
    Rule("UUFA_DB_ISIRS_RECEIVED_UNDUP",  sw("UUFA_DB_ISIRS_RECEIVED_UNDUP"),  "dashboard", "UUFA_DB_ISIRS_RECEIVED_UNDUP",  uosfa_name_fn=_db_uosfa_name, overwrite=True),
    Rule("UUFA_DB_ISIRS_RECEIVED_ALL",    sw("UUFA_DB_ISIRS_RECEIVED_ALL"),    "dashboard", "UUFA_DB_ISIRS_RECEIVED_ALL",    uosfa_name_fn=_db_uosfa_name, overwrite=True),
    Rule("UUFA_DB_ISIRS_LOADED_UNDUP",    sw("UUFA_DB_ISIRS_LOADED_UNDUP"),    "dashboard", "UUFA_DB_ISIRS_LOADED_UNDUP",    uosfa_name_fn=_db_uosfa_name, overwrite=True),
    Rule("UUFA_DB_ISIRS_LOADED_ALL",      sw("UUFA_DB_ISIRS_LOADED_ALL"),      "dashboard", "UUFA_DB_ISIRS_LOADED_ALL",      uosfa_name_fn=_db_uosfa_name, overwrite=True),
]
